sudo: required

language: bash

services:
  - docker

after_success:
  - echo "Pushing Docker images to Docker Hub..."
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PW"
  - ./build.sh
  - docker push bwv988/hadoop-base
  - docker push bwv988/hadoop-namenode
  - docker push bwv988/hadoop-datanode
