# Dockerfile for Hadoop namenode.

FROM analytics/hadoop-base

ENV HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
RUN mkdir -p /hadoop/dfs/name
VOLUME /hadoop/dfs/name

COPY provision/namenode-run.sh /namenode-run.sh
RUN chmod a+x /namenode-run.sh

CMD ["/namenode-run.sh"]
